name: Build and Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codeaz login
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push auth-streaming-server image
        uses: docker/build-push-action@v5
        with:
          context: ./auth-streaming-server
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/auth-streaming-server:latest

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/client:latest

      - name: Build and push mediasoup-server image
        uses: docker/build-push-action@v5
        with:
          context: ./mediasoup-server
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/mediasoup-server:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        run: |
          az container delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name auth-streaming-server --yes || true
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name auth-streaming-server \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/auth-streaming-server:latest \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label auth-streaming-server-${{ github.run_number }} \
            --ports 4000

          az container delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name client --yes || true
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name client \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/client:latest \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label client-${{ github.run_number }} \
            --ports 5173

          az container delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name mediasoup-server --yes || true
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name mediasoup-server \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/mediasoup-server:latest \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label mediasoup-server-${{ github.run_number }} \
            --ports 3000
